path:
  root: /home/maasyraf/Documents/research/ciha-enhancement/resources
  speech_dir: ${path.root}/clean_speech
  impulse_response_dir: ${path.root}/impulse_response
  noise_dir: ${path.root}/noise
  output_dir: ${path.root}/generated_data

sample_rate: 16000
